graph [
	comment ""
	directed 1
	node [ id 0 label "2" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 1 label "1" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 2 label "3" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 3 label "4" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 4 label "5" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 5 label "6" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 6 label "7" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 7 label "8" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 8 label "9" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 9 label "10" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 10 label "12" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 11 label "11" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 12 label "13" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 13 label "14" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 14 label "15" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 15 label "16" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 16 label "18" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 17 label "17" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 18 label "19" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 19 label "20" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 20 label "21" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 21 label "22" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 22 label "23" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 23 label "24" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 24 label "25" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 25 label "26" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 26 label "27" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 27 label "28" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 28 label "29" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 29 label "30" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 30 label "31" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 31 label "32" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 32 label "33" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 33 label "34" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 34 label "35" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 35 label "36" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 36 label "37" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 37 label "38" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 38 label "39" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 39 label "40" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 40 label "41" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 41 label "42" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 42 label "43" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 43 label "44" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 44 label "45" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 45 label "46" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 46 label "48" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 47 label "47" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 48 label "49" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 49 label "50" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 50 label "51" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 51 label "52" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 52 label "53" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 53 label "54" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 54 label "55" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 55 label "56" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 56 label "57" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 57 label "58" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 58 label "59" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 59 label "60" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 60 label "61" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 61 label "62" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 62 label "63" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 63 label "64" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 64 label "65" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 65 label "66" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 66 label "67" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 67 label "68" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 68 label "69" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 69 label "70" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 70 label "71" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 71 label "72" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 72 label "73" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 73 label "74" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 74 label "75" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 75 label "76" graphics [ fill "#ffffff" type "ellipse" ] ]
	node [ id 76 label "77" graphics [ fill "#ffffff" type "ellipse" ] ]
	edge [ source 0 target 1 ]
	edge [ source 2 target 1 ]
	edge [ source 3 target 1 ]
	edge [ source 3 target 2 ]
	edge [ source 4 target 1 ]
	edge [ source 5 target 1 ]
	edge [ source 6 target 1 ]
	edge [ source 7 target 1 ]
	edge [ source 8 target 1 ]
	edge [ source 9 target 1 ]
	edge [ source 10 target 1 ]
	edge [ source 10 target 2 ]
	edge [ source 10 target 3 ]
	edge [ source 10 target 11 ]
	edge [ source 12 target 10 ]
	edge [ source 13 target 10 ]
	edge [ source 14 target 10 ]
	edge [ source 15 target 10 ]
	edge [ source 16 target 17 ]
	edge [ source 18 target 17 ]
	edge [ source 18 target 16 ]
	edge [ source 19 target 17 ]
	edge [ source 19 target 16 ]
	edge [ source 19 target 18 ]
	edge [ source 20 target 17 ]
	edge [ source 20 target 16 ]
	edge [ source 20 target 18 ]
	edge [ source 20 target 19 ]
	edge [ source 21 target 17 ]
	edge [ source 21 target 16 ]
	edge [ source 21 target 18 ]
	edge [ source 21 target 19 ]
	edge [ source 21 target 20 ]
	edge [ source 22 target 17 ]
	edge [ source 22 target 16 ]
	edge [ source 22 target 18 ]
	edge [ source 22 target 19 ]
	edge [ source 22 target 20 ]
	edge [ source 22 target 21 ]
	edge [ source 23 target 10 ]
	edge [ source 23 target 12 ]
	edge [ source 23 target 17 ]
	edge [ source 23 target 16 ]
	edge [ source 23 target 18 ]
	edge [ source 23 target 19 ]
	edge [ source 23 target 20 ]
	edge [ source 23 target 21 ]
	edge [ source 23 target 22 ]
	edge [ source 24 target 10 ]
	edge [ source 24 target 23 ]
	edge [ source 25 target 10 ]
	edge [ source 25 target 23 ]
	edge [ source 25 target 24 ]
	edge [ source 26 target 10 ]
	edge [ source 26 target 17 ]
	edge [ source 26 target 24 ]
	edge [ source 26 target 25 ]
	edge [ source 27 target 10 ]
	edge [ source 27 target 23 ]
	edge [ source 27 target 24 ]
	edge [ source 27 target 25 ]
	edge [ source 27 target 26 ]
	edge [ source 28 target 10 ]
	edge [ source 28 target 27 ]
	edge [ source 29 target 10 ]
	edge [ source 29 target 23 ]
	edge [ source 29 target 27 ]
	edge [ source 30 target 23 ]
	edge [ source 31 target 10 ]
	edge [ source 31 target 23 ]
	edge [ source 31 target 27 ]
	edge [ source 31 target 30 ]
	edge [ source 32 target 10 ]
	edge [ source 33 target 10 ]
	edge [ source 33 target 27 ]
	edge [ source 34 target 10 ]
	edge [ source 34 target 29 ]
	edge [ source 35 target 10 ]
	edge [ source 35 target 29 ]
	edge [ source 35 target 34 ]
	edge [ source 36 target 10 ]
	edge [ source 36 target 29 ]
	edge [ source 36 target 34 ]
	edge [ source 36 target 35 ]
	edge [ source 37 target 10 ]
	edge [ source 37 target 29 ]
	edge [ source 37 target 34 ]
	edge [ source 37 target 35 ]
	edge [ source 37 target 36 ]
	edge [ source 38 target 10 ]
	edge [ source 38 target 29 ]
	edge [ source 38 target 34 ]
	edge [ source 38 target 35 ]
	edge [ source 38 target 36 ]
	edge [ source 38 target 37 ]
	edge [ source 39 target 25 ]
	edge [ source 40 target 25 ]
	edge [ source 41 target 24 ]
	edge [ source 41 target 25 ]
	edge [ source 42 target 24 ]
	edge [ source 42 target 25 ]
	edge [ source 42 target 41 ]
	edge [ source 43 target 10 ]
	edge [ source 43 target 26 ]
	edge [ source 43 target 27 ]
	edge [ source 44 target 10 ]
	edge [ source 44 target 28 ]
	edge [ source 45 target 28 ]
	edge [ source 46 target 47 ]
	edge [ source 48 target 10 ]
	edge [ source 48 target 25 ]
	edge [ source 48 target 27 ]
	edge [ source 48 target 46 ]
	edge [ source 49 target 10 ]
	edge [ source 49 target 26 ]
	edge [ source 50 target 24 ]
	edge [ source 50 target 49 ]
	edge [ source 51 target 10 ]
	edge [ source 51 target 26 ]
	edge [ source 51 target 49 ]
	edge [ source 52 target 39 ]
	edge [ source 52 target 51 ]
	edge [ source 53 target 51 ]
	edge [ source 54 target 26 ]
	edge [ source 54 target 49 ]
	edge [ source 54 target 51 ]
	edge [ source 55 target 10 ]
	edge [ source 55 target 17 ]
	edge [ source 55 target 25 ]
	edge [ source 55 target 26 ]
	edge [ source 55 target 39 ]
	edge [ source 55 target 41 ]
	edge [ source 55 target 48 ]
	edge [ source 55 target 49 ]
	edge [ source 55 target 51 ]
	edge [ source 55 target 54 ]
	edge [ source 56 target 49 ]
	edge [ source 56 target 55 ]
	edge [ source 57 target 41 ]
	edge [ source 57 target 48 ]
	edge [ source 57 target 55 ]
	edge [ source 58 target 10 ]
	edge [ source 58 target 27 ]
	edge [ source 58 target 48 ]
	edge [ source 58 target 55 ]
	edge [ source 58 target 57 ]
	edge [ source 59 target 48 ]
	edge [ source 59 target 55 ]
	edge [ source 59 target 57 ]
	edge [ source 59 target 58 ]
	edge [ source 60 target 48 ]
	edge [ source 60 target 58 ]
	edge [ source 60 target 59 ]
	edge [ source 61 target 48 ]
	edge [ source 61 target 55 ]
	edge [ source 61 target 57 ]
	edge [ source 61 target 58 ]
	edge [ source 61 target 59 ]
	edge [ source 61 target 60 ]
	edge [ source 62 target 41 ]
	edge [ source 62 target 48 ]
	edge [ source 62 target 55 ]
	edge [ source 62 target 57 ]
	edge [ source 62 target 58 ]
	edge [ source 62 target 59 ]
	edge [ source 62 target 60 ]
	edge [ source 62 target 61 ]
	edge [ source 63 target 48 ]
	edge [ source 63 target 55 ]
	edge [ source 63 target 57 ]
	edge [ source 63 target 58 ]
	edge [ source 63 target 59 ]
	edge [ source 63 target 60 ]
	edge [ source 63 target 61 ]
	edge [ source 63 target 62 ]
	edge [ source 64 target 10 ]
	edge [ source 64 target 48 ]
	edge [ source 64 target 55 ]
	edge [ source 64 target 57 ]
	edge [ source 64 target 58 ]
	edge [ source 64 target 59 ]
	edge [ source 64 target 60 ]
	edge [ source 64 target 61 ]
	edge [ source 64 target 62 ]
	edge [ source 64 target 63 ]
	edge [ source 65 target 48 ]
	edge [ source 65 target 55 ]
	edge [ source 65 target 57 ]
	edge [ source 65 target 58 ]
	edge [ source 65 target 59 ]
	edge [ source 65 target 60 ]
	edge [ source 65 target 61 ]
	edge [ source 65 target 62 ]
	edge [ source 65 target 63 ]
	edge [ source 65 target 64 ]
	edge [ source 66 target 48 ]
	edge [ source 66 target 58 ]
	edge [ source 66 target 59 ]
	edge [ source 66 target 60 ]
	edge [ source 66 target 61 ]
	edge [ source 66 target 62 ]
	edge [ source 66 target 63 ]
	edge [ source 66 target 64 ]
	edge [ source 66 target 65 ]
	edge [ source 67 target 57 ]
	edge [ source 68 target 10 ]
	edge [ source 68 target 24 ]
	edge [ source 68 target 25 ]
	edge [ source 68 target 27 ]
	edge [ source 68 target 41 ]
	edge [ source 68 target 48 ]
	edge [ source 69 target 10 ]
	edge [ source 69 target 24 ]
	edge [ source 69 target 25 ]
	edge [ source 69 target 27 ]
	edge [ source 69 target 41 ]
	edge [ source 69 target 48 ]
	edge [ source 69 target 68 ]
	edge [ source 70 target 10 ]
	edge [ source 70 target 24 ]
	edge [ source 70 target 25 ]
	edge [ source 70 target 27 ]
	edge [ source 70 target 41 ]
	edge [ source 70 target 58 ]
	edge [ source 70 target 68 ]
	edge [ source 70 target 69 ]
	edge [ source 71 target 10 ]
	edge [ source 71 target 25 ]
	edge [ source 71 target 27 ]
	edge [ source 71 target 41 ]
	edge [ source 71 target 48 ]
	edge [ source 71 target 68 ]
	edge [ source 71 target 69 ]
	edge [ source 71 target 70 ]
	edge [ source 72 target 10 ]
	edge [ source 72 target 26 ]
	edge [ source 72 target 27 ]
	edge [ source 73 target 48 ]
	edge [ source 74 target 48 ]
	edge [ source 74 target 73 ]
	edge [ source 75 target 25 ]
	edge [ source 75 target 41 ]
	edge [ source 75 target 48 ]
	edge [ source 75 target 68 ]
	edge [ source 75 target 69 ]
	edge [ source 75 target 70 ]
	edge [ source 75 target 71 ]
	edge [ source 76 target 48 ]
	edge [ source 76 target 58 ]
	edge [ source 76 target 62 ]
	edge [ source 76 target 63 ]
	edge [ source 76 target 64 ]
	edge [ source 76 target 65 ]
	edge [ source 76 target 66 ]
]